// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProvaVida.Infrastructure.Persistence;

#nullable disable

namespace ProvaVida.Infrastructure.Migrations
{
    [DbContext(typeof(ProvaVidaDbContext))]
    partial class ProvaVidaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProvaVida.Domain.Entities.PerfilBiometrico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CadastradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ContribuinteId")
                        .HasColumnType("uuid");

                    b.Property<string>("FaceEmbeddingJson")
                        .HasColumnType("text");

                    b.Property<string>("FaceHashReferencia")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Nuit")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.HasKey("Id");

                    b.HasIndex("ContribuinteId")
                        .IsUnique();

                    b.HasIndex("Nuit");

                    b.ToTable("PerfisBiometricos", (string)null);
                });

            modelBuilder.Entity("ProvaVida.Domain.Entities.RegistroProvaVida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContribuinteId")
                        .HasColumnType("uuid");

                    b.Property<string>("FaceHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("MovimentosDetectados")
                        .HasColumnType("boolean");

                    b.Property<string>("Nuit")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RealizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ScoreLiveness")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ContribuinteId");

                    b.HasIndex("Nuit");

                    b.ToTable("RegistrosProvaVida", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
