FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY src/Contribuintes.Domain/Contribuintes.Domain.csproj src/Contribuintes.Domain/
COPY src/Contribuintes.Application/Contribuintes.Application.csproj src/Contribuintes.Application/
COPY src/Contribuintes.Infrastructure/Contribuintes.Infrastructure.csproj src/Contribuintes.Infrastructure/
COPY src/Contribuintes.Api/Contribuintes.Api.csproj src/Contribuintes.Api/
RUN dotnet restore src/Contribuintes.Api/Contribuintes.Api.csproj

COPY src/ src/
RUN dotnet publish src/Contribuintes.Api/Contribuintes.Api.csproj -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENTRYPOINT ["dotnet", "Contribuintes.Api.dll"]
